export const LOAD_QUESTIONS = 'LOAD_QUESTIONS';
export const LOAD_USER_QUESTIONS = 'LOAD_USER_QUESTIONS';
export const LOAD_USER_QUESTIONS_STARTED = 'LOAD_USER_QUESTIONS_STARTED';
export const LOAD_USER_QUESTIONS_FAILED = 'LOAD_USER_QUESTIONS_FAILED';
export const QUESTIONS_LOADING = 'QUESTIONS_LOADING';
export const UPVOTE_QUESTION = 'UPVOTE_QUESTION';
export const POST_ANSWER = 'POST_ANSWER';
export const POST_ANSWER_FAILED = 'POST_ANSWER_FAILED';
export const LOAD_QUESTIONS_FAILED = 'LOAD_QUESTIONS_FAILED';
export const POST_QUESTION = 'POST_QUESTION';
export const POST_QUESTION_FAILED = 'POST_QUESTION_FAILED';
export const UPVOTE_QUESTION_FAILED = 'UPVOTE_QUESTION_FAILED';



// Space types
export const SPACES_LOADING = 'SPACES_LOADING';
export const LOAD_SPACES = 'LOAD_SPACES';
export const LOAD_SPACES_FAILED = 'LOAD_SPACES_FAILED';
export const SPACE_QUESTIONS_LOADING = 'SPACE_QUESTIONS_LOADING';
export const LOAD_SPACE_QUESTIONS = 'LOAD_SPACE_QUESTIONS';
export const LOAD_SPACE_QUESTIONS_FAILED = 'LOAD_SPACE_QUESTIONS_FAILED'
export const SPACE_JOIN_FAILED = 'SPACE_JOIN_FAILED'
export const SPACE_JOIN_SUCCESS = 'SPACE_JOIN_SUCCESS'
export const SPACE_JOIN_LOADING = 'SPACE_JOIN_LOADING';
export const POST_SPACE_QUESTION = 'POST_SPACE_QUESTION';
export const POST_SPACE_QUESTION_FAILED = 'POST_SPACE_QUESTION_FAILED';


// Question types
export const LOGIN = 'LOGIN';
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';
